# This is a basic workflow that is manually triggered

name: Build and Deploy Ionic App

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SERVICE_NAME: ionic-app
  IMAGE_NAME: frontend
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and deploy Ionic App
    runs-on: ubuntu-latest
    steps:
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build App
        run: |
          cd wolkesieben
          npm install
          ionic build --prod
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          credentials: ${{ env.GCP_SA_KEY }}
          path: wolkesieben/www
          destination: wolkesieben-frontend
